# Sample App For Testing 
# Taking from https://learn.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-new
# kubectl apply -f https://raw.githubusercontent.com/Azure/application-gateway-kubernetes-ingress/master/docs/examples/aspnetapp.yaml

apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp
  labels:
    app: aspnetapp
spec:
  containers:
  - image: "mcr.microsoft.com/dotnet/samples:aspnetapp"
    name: aspnetapp-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: aspnetapp
spec:
  selector:
    app: aspnetapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: aspnetapp
#  annotations:
#    kubernetes.io/ingress.class: azure/application-gateway
#spec:
#  rules:
#  - http:
#      paths:
#     - path: /
#       backend:
#         service:
#           name: aspnetapp
#           port:
#             number: 80
#       pathType: Exact
#---
#apiVersion: networking.x-k8s.io/v1alpha1
#kind: Gateway
#metadata:
#  name: aspnetapp-gateway
#spec:
#  listeners:
#   - protocol: HTTP
#     port: 80
#     routes:
#       - selector:
#           matchLabels:
#             app: aspnetapp
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: aspnetapp-route
spec:
  rules:
    - host: "*"
      http:
        paths:
          - path: /
            backend:
              serviceName: aspnetapp
              servicePort: 80
