# Sample App For Testing 
# Taking from https://learn.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-new
# kubectl apply -f https://raw.githubusercontent.com/Azure/application-gateway-kubernetes-ingress/master/docs/examples/aspnetapp.yaml

apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp
  labels:
    app: aspnetapp
spec:
  containers:
  - image: "mcr.microsoft.com/dotnet/samples:aspnetapp"
    name: aspnetapp-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: aspnetapp
spec:
  selector:
    app: aspnetapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway-01
  #namespace: test-infra
  annotations:
    alb.networking.azure.io/alb-id: /subscriptions/$SUB/resourcegroups/AKS_RG/providers/Microsoft.ServiceNetworking/trafficControllers/AGW-C01
    #replace $SUBID with your subscription id in agfc reource id 
    #alb.networking.azure.io/alb-id: $RESOURCE_ID ##invalid ID 

spec:
  gatewayClassName: azure-alb-external
  listeners:
  - name: http-listener
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
  addresses:
  - type: alb.networking.azure.io/alb-frontend
    value: AGW-FE01 #FrontEnd

---
apiVersion: alb.networking.azure.io/v1
kind: BackendTLSPolicy
metadata:
  name: aspnet-app-tls-policy
  #namespace: test-infra
spec:
  targetRef:
    group: ""
    kind: Service
    name: aspnet
    #namespace: test-infra
  default:
    sni: aspnet.backend.com
    ports:
    - port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: aspnet-route
  #namespace: test-infra
spec:
  parentRefs:
  - name: gateway-01
  hostnames:
  - "aspnet.backend.com"
  rules:
  - backendRefs:
    - name: aspnetapp
      port: 80
